[package]
name = "volumen_parser_php"
version = "0.2.0"
edition = "2021"
description = "Volumen PHP parser using Tree-sitter"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[dependencies]
tree-sitter = "0.26.3"
tree-sitter-php = "0.24.2"
volumen_parser_core = { version = "0.2.0", path = "../parser-core" }
volumen_types = { version = "0.2.0", path = "../types-crate" }
