[package]
publish = false
name = "volumen-wasm"
version = "0.2.0"
edition = "2024"
description = "Volumen Wasm crate"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.106"
# Volumen
volumen_types = { version = "0.2.0", path = "../types-crate" }
volumen_parser = { version = "0.2.0", path = "../parser" }
serde-wasm-bindgen = "0.6.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.56"
indoc = "2.0.6"
pretty_assertions = "1.4"
