[package]
name = "volumen_parser_test"
version = "0.3.3"
edition = "2024"
description = "Volumen parser test helpers crate"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[dependencies]
volumen_types = { version = "0.3.3", path = "../types-crate" }
pretty_assertions = "1.4.1"
