[package]
name = "volumen_benchmarks"
version = "0.3.3"
edition = "2021"
publish = false

[[bench]]
name = "python_parsers"
harness = false

[[bench]]
name = "typescript_parsers"
harness = false

[[bench]]
name = "ruby_parsers"
harness = false

[[bench]]
name = "php_parsers"
harness = false

[[bench]]
name = "go_parsers"
harness = false

[[bench]]
name = "java_parsers"
harness = false

[[bench]]
name = "csharp_parsers"
harness = false

[[bin]]
name = "bench-report"
path = "src/bin/bench-report.rs"

[[bin]]
name = "calculate-tokens"
path = "src/bin/calculate-tokens.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }
tree-sitter = { git = "https://github.com/kossnocorp/tree-sitter", branch = "wasm-malloc" }
tree-sitter-go = { git = "https://github.com/kossnocorp/tree-sitter-go", branch = "wasm-repro-malloc" }
tree-sitter-java = { git = "https://github.com/kossnocorp/tree-sitter-java", branch = "wasm-repro-malloc" }
tree-sitter-c-sharp = { git = "https://github.com/kossnocorp/tree-sitter-c-sharp", branch = "wasm-repro-malloc" }
tree-sitter-php = { git = "https://github.com/kossnocorp/tree-sitter-php", branch = "wasm-repro-malloc" }
tree-sitter-ruby = { git = "https://github.com/kossnocorp/tree-sitter-ruby", branch = "wasm-repro-malloc" }
tree-sitter-python = { git = "https://github.com/kossnocorp/tree-sitter-python", branch = "wasm-repro-malloc" }
tree-sitter-typescript = { git = "https://github.com/kossnocorp/tree-sitter-typescript", branch = "wasm-repro-malloc" }
volumen_parser_core = { version = "0.3.3", path = "../parser-core" }
volumen_parser_py = { version = "0.3.3", path = "../parser-py" }
volumen_parser_py_ruff = { version = "0.3.3", path = "../parser-py-ruff" }
volumen_parser_py_tree_sitter = { version = "0.3.3", path = "../parser-py-tree-sitter" }
volumen_parser_ts = { version = "0.3.3", path = "../parser-ts" }
volumen_parser_ts_tree_sitter = { version = "0.3.3", path = "../parser-ts-tree-sitter" }
volumen_parser_rb = { version = "0.3.3", path = "../parser-rb" }
volumen_parser_php = { version = "0.3.3", path = "../parser-php" }
volumen_parser_go = { version = "0.3.3", path = "../parser-go" }
volumen_parser_java = { version = "0.3.3", path = "../parser-java" }
volumen_parser_cs = { version = "0.3.3", path = "../parser-cs" }
volumen_types = { version = "0.3.3", path = "../types-crate" }
