[package]
name = "volumen_parser_py_tree_sitter"
version = "0.1.0"
edition = "2024"
description = "Volumen Python parser using Tree-sitter"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[dependencies]
serde = "1.0.219"
# Volumen
volumen_types = { version = "0.2.0", path = "../types-crate" }
volumen_parser_core = { version = "0.2.0", path = "../parser-core" }
# Tree-sitter
tree-sitter = "0.25"
tree-sitter-python = "0.25"

[dev-dependencies]
indoc = "2.0.6"
insta = { version = "1.43.1" }
volumen_parser_test = { version = "0.2.0", path = "../parser-test" }
