[package]
edition = "2024"
description = "Volumen types"
license = "MIT"
name = "volumen_types"
repository = "https://github.com/kossnocorp/volumen"
version = "0.3.3"

[dependencies]
serde = { version = "1", features = ["derive"] }
litty = "0.2"

