[package]
name = "volumen_parser_ts_tree_sitter"
version = "0.3.3"
edition = "2024"
description = "Volumen TypeScript parser using Tree-sitter"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[dependencies]
serde = "1.0.219"
# Volumen
volumen_types = { version = "0.3.3", path = "../types-crate" }
volumen_parser_core = { version = "0.3.3", path = "../parser-core" }
# Tree-sitter
tree-sitter = { git = "https://github.com/kossnocorp/tree-sitter", branch = "wasm-malloc" }
tree-sitter-typescript = { git = "https://github.com/kossnocorp/tree-sitter-typescript", branch = "wasm-repro-malloc" }

[dev-dependencies]
indoc = "2.0.6"
insta = { version = "1.43.1" }
volumen_parser_test = { version = "0.3.3", path = "../parser-test" }
