[package]
publish = false
name = "volumen_parser_py"
version = "0.3.3"
edition = "2024"
description = "Volumen Python parser crate (Ruff-based)"
repository = "https://github.com/kossnocorp/volumen"
license = "MIT"

[dependencies]
serde = "1.0.219"
# Volumen
volumen_types = { version = "0.3.3", path = "../types-crate" }
volumen_parser_core = { version = "0.3.3", path = "../parser-core" }
# Ruff
ruff_python_ast = { git = "https://github.com/astral-sh/ruff/", rev = "0.12.12" }
ruff_python_parser = { git = "https://github.com/astral-sh/ruff/", rev = "0.12.12" }
ruff_python_trivia = { git = "https://github.com/astral-sh/ruff/", rev = "0.12.12" }
ruff_text_size = { git = "https://github.com/astral-sh/ruff/", rev = "0.12.12" }

[dev-dependencies]
indoc = "2.0.6"
insta = { version = "1.43.1" }
volumen_parser_test = { version = "0.3.3", path = "../parser-test" }
